name: 'Lock Threads'
description: 'Lock closed issues and pull requests after a period of inactivity'
author: 'Armin Sebastian'
inputs:
  github-token:
    description: 'GitHub access token'
    required: true
  issue-lock-inactive-days:
    description: 'Number of days of inactivity before a closed issue is locked'
    default: '365'
  issue-exclude-created-before:
    description: 'Do not lock issues created before a given timestamp, value must follow ISO 8601'
    default: ''
  issue-include-labels:
    description: 'Only lock issues with these labels, value must be a comma separated list of labels'
    default: ''
  issue-exclude-labels:
    description: 'Do not lock issues with these labels, value must be a comma separated list of labels'
    default: ''
  issue-lock-labels:
    description: 'Labels to add before locking an issue, value must be a comma separated list of labels'
    default: ''
  issue-lock-comment:
    description: 'Comment to post before locking an issue'
    default: ''
  issue-lock-reason:
    description: 'Reason for locking an issue, value must be one of `resolved`, `off-topic`, `too heated` or `spam`'
    default: 'resolved'
  pr-lock-inactive-days:
    description: 'Number of days of inactivity before a closed pull request is locked'
    default: '365'
  pr-exclude-created-before:
    description: 'Do not lock pull requests created before a given timestamp, value must follow ISO 8601'
    default: ''
  pr-include-labels:
    description: 'Only lock pull requests with these labels, value must be a comma separated list of labels'
    default: ''
  pr-exclude-labels:
    description: 'Do not lock pull requests with these labels, value must be a comma separated list of labels'
    default: ''
  pr-lock-labels:
    description: 'Labels to add before locking a pull request, value must be a comma separated list of labels'
    default: ''
  pr-lock-comment:
    description: 'Comment to post before locking a pull request'
    default: ''
  pr-lock-reason:
    description: 'Reason for locking a pull request, value must be one of `resolved`, `off-topic`, `too heated` or `spam`'
    default: 'resolved'
  process-only:
    description: 'Limit locking to only issues or pull requests, value must be one of `issues` or `prs`'
    default: ''
outputs:
  issues:
    description: 'Issues that have been locked, value is a JSON string'
  prs:
    description: 'Pull requests that have been locked, value is a JSON string'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'gray-dark'
